### ISSUE TITLE
Will not compile in Grails 2.4.3

### ISSUE THREAD

**Issue by sbglasius** [halfbaked/grails-font-awesome-resources#29]
Hi,

Just included the plugin into my Grails 2.4.3 application, but it will not compile due to a dependency on the resources plugin. I do not use the resources plugin anymore.

Error is here

```
Compilation error: startup failed:
/Users/sbg/projects/calnet/ucidentity/guest-sponsor-app/target/work/plugins/font-awesome-resources-4.1.0.1/grails-app/resourceMappers/FontAwesomePluginResourceMapper.groovy: 1: unable to resolve class org.grails.plugin.resource.mapper.MapperPhase
 @ line 1, column 1.
   import org.grails.plugin.resource.mapper.MapperPhase
   ^

/Users/sbg/projects/calnet/ucidentity/guest-sponsor-app/target/work/plugins/font-awesome-resources-4.1.0.1/grails-app/resourceMappers/FontAwesomePluginResourceMapper.groovy: 9: unable to resolve class org.grails.plugin.resource.mapper.MapperPhase 
 @ line 9, column 20.
       static phase = MapperPhase.ALTERNATEREPRESENTATION
                      ^

2 errors
```

I will try to see if I can fix it and submit a pull request.
